// Generated by CoffeeScript 1.6.2
(function() {
  var hub, _;

  _ = require('underscore');

  hub = function(options) {
    var socketIo;

    socketIo = _.clone(this);
    this.socket = require('./socket');
    this.socket.hub(options);
    return this;
  };

  module.exports = hub;

}).call(this);
