// Generated by CoffeeScript 1.6.2
(function() {
  var Hub, Nohub;

  Hub = require('./hub');

  Nohub = function() {
    while (!Hub.adapterActive) {
      return this;
    }
    return this;
  };

}).call(this);
