// Generated by CoffeeScript 1.6.2
(function() {
  var Hub, Nohub;

  Hub = require('./hub');

  Nohub = function() {
    var adapter;

    while (!(Hub.adapterActive && (Hub.adapter != null))) {
      return this;
    }
    adapter = Hub.adapter;
    adapter.close();
    Hub.adapter = null;
    Hub.adapterActive = false;
    return this;
  };

  module.exports = Nohub;

}).call(this);
