// Generated by CoffeeScript 1.6.2
(function() {
  var socketIo;

  socketIo = require('socket.io');

  socketIo.hub = require('./hub');

  socketIo.nohub = require('./nohub');

  module.exports = socketIo;

}).call(this);
