// Generated by CoffeeScript 1.6.2
(function() {
  var Socket, adapter, adapterActive, adapters, exports, _,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Socket = require('socket.io/lib/socket');

  adapter = null;

  adapterActive = false;

  adapters = ['redis'];

  _ = require('underscore');

  Socket.hub = function(options) {
    var Adapter, adapterName;

    adapterName = options.adapter || 'redis';
    if (__indexOf.call(adapters, adapterName) < 0) {
      throw "adapter " + adapter + " is not exist!";
    }
    Adapter = require("./" + adapterName + "-adapter");
    adapter = new Adapter(options);
    adapter.sub('socket.io.hub');
    adapterActive = true;
    return this;
  };

  Socket.prototype.subscribe = function() {
    var _this = this;

    if (adapterActive && !this.isSubscribed) {
      this.isSubscribed = true;
      return adapter.on(function(data) {
        if (_this.id !== data.socketId) {
          delete data.socketId;
          return _this.$$emit.apply(_this, _.toArray(data));
        }
      });
    }
  };

  Socket.nohub = function() {
    adapter.close();
    adapterActive = false;
    return this;
  };

  Socket.prototype.$$emit = Socket.prototype.emit;

  Socket.prototype.emit = function(ev) {
    var data;

    if (adapterActive) {
      data = _.clone(arguments);
      data.socketId = this.id;
      adapter.pub('socket.io.hub', data);
    }
    return this.$$emit.apply(this, arguments);
  };

  exports = module.exports = Socket;

}).call(this);
